# Generated by Django 6.1 on 2026-09-01 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep_origin', models.CharField(max_length=8)),
                ('city_origin', models.CharField(max_length=50)),
                ('uf_origin', models.CharField(max_length=2)),
                ('cep_destination', models.CharField(max_length=8)),
                ('city_destination', models.CharField(max_length=50)),
                ('uf_destination', models.CharField(max_length=2)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuoteOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_days', models.PositiveIntegerField()),
                ('raw_response', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quotes.provider')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='quotes.quote')),
            ],
        ),
    ]
