# Generated by Django 6.1 on 2026-09-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='cep_destination',
            field=models.CharField(db_index=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='quote',
            name='cep_origin',
            field=models.CharField(db_index=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='quoteoption',
            name='raw_response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
